/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;


public class App {
    public static void main(String[] args) {
        Gson gson = new Gson();
        try {
            Reader reader = new FileReader("app/src/main/resources/data.json");
            Quotes[] q1 = gson.fromJson(reader,Quotes[].class);
            int min = 0;
            int max = q1.length-1;
            int b = (int)(Math.random()*(max-min+1)+min);
            System.out.println(q1[0].toString());
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
